/*https://www.hackerrank.com/challenges/the-report/problem*/
SELECT 
If(GRADES.Grade<8,STUDENTS.Name=null,STUDENTS.Name),GRADES.Grade,STUDENTS.MARKS 
FROM STUDENTS INNER JOIN GRADES ON STUDENTS.Marks BETWEEN GRADES.Min_Mark AND GRADES.Max_Mark
ORDER BY GRADES.GRADE DESC,STUDENTS.NAME  
